// <auto-generated />
namespace ATLAS_ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCargoPermissaoSystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCargoPermissaoSystem));
        
        string IMigrationMetadata.Id
        {
            get { return "202605272310245_AddCargoPermissaoSystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
