// <auto-generated />
namespace ATLAS_ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NormalizarDocumentos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NormalizarDocumentos));

        string IMigrationMetadata.Id
        {
            get { return "20260525002000_NormalizarDocumentos"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
